name: Sample Template

on:
  workflow_call:
    inputs:
      my_input:
        description: 'An example input'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print input
        run: echo "Input received:${{ inputs.my_input }}"

